# Generated by Django 4.0 on 2022-11-14 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sa', '0002_deneme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='deneme',
        ),
    ]
