# Generated by Django 4.0 on 2022-11-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sa', '0003_delete_deneme'),
    ]

    operations = [
        migrations.CreateModel(
            name='odeme',
            fields=[
                ('kullanici_id', models.AutoField(primary_key=True, serialize=False)),
                ('kart_no', models.CharField(max_length=16)),
                ('kart_skt', models.CharField(max_length=4)),
                ('kart_cvv', models.CharField(max_length=3)),
            ],
        ),
        migrations.RenameField(
            model_name='adres',
            old_name='id',
            new_name='adress_id',
        ),
    ]
