# Generated by Django 4.0 on 2022-11-17 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sa', '0004_odeme_rename_id_adres_adress_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='odeme',
        ),
    ]
