# Generated by Django 4.0 on 2022-11-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sa', '0005_delete_odeme'),
    ]

    operations = [
        migrations.CreateModel(
            name='odeme',
            fields=[
                ('kart_id', models.AutoField(primary_key=True, serialize=False)),
                ('kullanici_id', models.CharField(max_length=15)),
                ('kart_no', models.CharField(max_length=16)),
                ('kart_skt', models.CharField(max_length=4)),
                ('kart_cvv', models.CharField(max_length=3)),
            ],
        ),
    ]
