# Generated by Django 4.0 on 2022-11-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sa', '0006_odeme'),
    ]

    operations = [
        migrations.CreateModel(
            name='sepet',
            fields=[
                ('sepet_id', models.AutoField(primary_key=True, serialize=False)),
                ('kiyafet_id', models.IntegerField(max_length=10)),
                ('kiyafet_title', models.CharField(max_length=150)),
                ('kiyafet_desc', models.CharField(max_length=200)),
                ('sepet_toplam_fiyat', models.CharField(max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='adres',
            name='kullanici_id',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='odeme',
            name='kullanici_id',
            field=models.IntegerField(max_length=10),
        ),
    ]
