# Generated by Django 4.0 on 2022-11-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sa', '0007_sepet_alter_adres_kullanici_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adres',
            name='kullanici_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='kiyafet',
            name='kiyafet_fiyat',
            field=models.FloatField(max_length=8),
        ),
        migrations.AlterField(
            model_name='odeme',
            name='kullanici_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sepet',
            name='kiyafet_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='kullanici_id',
            field=models.IntegerField(),
        ),
    ]
